# permissions for end users to view keeperclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clickhouse-operator
    app.kubernetes.io/managed-by: kustomize
  name: keepercluster-viewer-role
rules:
- apiGroups:
  - clickhouse.com
  resources:
  - keeperclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - clickhouse.com
  resources:
  - keeperclusters/status
  verbs:
  - get
